services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    ports:
      - 27017:27017

  mongo-e2e:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: roote2e
      MONGO_INITDB_ROOT_PASSWORD: roote2e123
    ports:
      - 27017:27017
