name: API CI
#on: [push]
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  uni-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: install
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash
        run: npm run test

  eslint-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: install
        shell: bash
        run: npm ci
      - name: run eslint test
        shell: bash
        run: npm run lint

  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:20

    services:
      mongo-e2e:
        image: mongo:4.4
        env:
          MONGO_INITDB_ROOT_USERNAME: roote2e
          MONGO_INITDB_ROOT_PASSWORD: roote2e123
        ports:
          - 27017:27017
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        shell: bash
        run: npm ci
      - name: run e2e
        shell: bash
        run: npm run test:e2e
        env:
          MONGO_DB_NAME: demo
          MONGO_URL: mongodb://roote2e:roote2e123@mongo-e2e:27017?retryWrites=true&writeConcern=majority
